export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const ADD_USER = "ADD_USER";
export const SET_USER_AFTER_LOADING_FROM_LOCALSTORAGE =
  "SET_USER_AFTER_LOADING_FROM_LOCALSTORAGE";
export const SORT_USERS_BY_PHONE_NUMBER = "SORT_USERS_BY_PHONE_NUMBER";
export const SORT_USERS_BY_NAME = "SORT_USERS_BY_NAME";
